#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-sphinx_ansible_theme
Version  : 0.9.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/ee/df/e60542b260c71b9e8c39647a0f3605d44500012dbcc235f69880abe626c8/sphinx-ansible-theme-0.9.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/ee/df/e60542b260c71b9e8c39647a0f3605d44500012dbcc235f69880abe626c8/sphinx-ansible-theme-0.9.1.tar.gz
Summary  : Ansible Sphinx Theme
Group    : Development/Tools
License  : MIT
Requires: pypi-sphinx_ansible_theme-license = %{version}-%{release}
Requires: pypi-sphinx_ansible_theme-python = %{version}-%{release}
Requires: pypi-sphinx_ansible_theme-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(ansible_pygments)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(setuptools_scm_git_archive)
BuildRequires : pypi(sphinx)
BuildRequires : pypi(sphinx_rtd_theme)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
sphinx_ansible_theme
--------------------
A reusable Ansible Sphinx Theme.
Demo-site at https://sphinx-ansible-theme.readthedocs.io/en/latest/

%package license
Summary: license components for the pypi-sphinx_ansible_theme package.
Group: Default

%description license
license components for the pypi-sphinx_ansible_theme package.


%package python
Summary: python components for the pypi-sphinx_ansible_theme package.
Group: Default
Requires: pypi-sphinx_ansible_theme-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinx_ansible_theme package.


%package python3
Summary: python3 components for the pypi-sphinx_ansible_theme package.
Group: Default
Requires: python3-core
Provides: pypi(sphinx_ansible_theme)
Requires: pypi(ansible_pygments)
Requires: pypi(sphinx)
Requires: pypi(sphinx_rtd_theme)

%description python3
python3 components for the pypi-sphinx_ansible_theme package.


%prep
%setup -q -n sphinx-ansible-theme-0.9.1
cd %{_builddir}/sphinx-ansible-theme-0.9.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644192876
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinx_ansible_theme
cp %{_builddir}/sphinx-ansible-theme-0.9.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinx_ansible_theme/49687825ac9028274cd37f2294743fd3d4eaf1fd
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinx_ansible_theme/49687825ac9028274cd37f2294743fd3d4eaf1fd

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
